title: R for Geospatial
description: Desenvolvimento de Scripts e Webapps com o R
show_downloads: false

baseurl: "/geostats" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://geosaber.github.io" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
geostats:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Sidney Goveia"
image: /thumbnail-jumbo.png

#  site:
facebook:
  profile_id: 509351975782055
  
#  admins:
